### ISSUE TITLE
How to add gaps?

### ISSUE THREAD

**Issue by tejasnishad** [fehawen/vswm#1]
Hi, I'm wondering how to add gaps. I don't know C, so I'm having a hard time figuring it out on my own. Help will be appreciated!

**Comment by fehawen** [comment]
Hi there. Gaps is relatively easy to implement. I did actually have it in an earlier version, so it's just a matter of adding that back in again. Unfortunately, I don't have time to do it right now, but I'd be happy to do it in a couple of days. That'd be OK?

**Comment by tejasnishad** [comment]
Of course.

**Comment by tejasnishad** [comment]
Also, thanks for mentioning the earlier version. I found the earlier file in your commit history and it works fine.
